name: daily_bonus

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:
  #测试使用,取消下面2个#注释,star触发执行actions,如果成功,最好再注释掉,免得别人star就给你签到    
  #watch:
  #  types: [started]
jobs:
  main:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: node main.js 
        env:
            cookie: ${{secrets.COOKIE}}
      - name: show result
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: ./result
